apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-resources
  labels:
    app: nginx
    type: resource-limited
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe: 
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5 

