apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-with-config
  labels:
    app: web-app-config
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app-config
  template:
    metadata:
      labels:
        app: web-app-config
    spec:
      containers:
      - name: web-app
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        # Environment variables from ConfigMap
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: database_url
        - name: DEBUG_MODE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: debug_mode
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app_name
        volumeMounts:
        # Mount entire ConfigMap as volume
        - name: config-volume
          mountPath: /etc/config
        # Mount specific files
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: web-content
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: config-volume
        configMap:
          name: app-config
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: web-content
        configMap:
          name: nginx-config
