apiVersion: v1
kind: Service
metadata:
  name: nginx-headless-service
  labels:
    app: nginx
    service-type: headless
spec:
  clusterIP: None  # This makes it headless
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
