apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limit-range
  namespace: resource-constrained
spec:
  limits:
  - default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: 1000m
      memory: 1Gi
    min:
      cpu: 50m
      memory: 64Mi
    type: Container
  - max:
      cpu: 2000m
      memory: 2Gi
    min:
      cpu: 100m
      memory: 128Mi
    type: Pod
---
apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-limit-range
  namespace: resource-constrained
spec:
  limits:
  - default:
      storage: 2Gi
    defaultRequest:
      storage: 1Gi
    max:
      storage: 10Gi
    min:
      storage: 100Mi
    type: PersistentVolumeClaim
---
# Test pod that should get default limits
apiVersion: v1
kind: Pod
metadata:
  name: default-limits-pod
  namespace: resource-constrained
spec:
  containers:
  - name: app
    image: busybox:1.35
    command: ["sleep", "3600"]
    # No resources specified - should get defaults from LimitRange