apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
  labels:
    app: pvc-demo
spec:
  containers:
  - name: app
    image: nginx:1.21
    ports:
    - containerPort: 80
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
    - name: web-content
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: my-pvc
  - name: web-content
    persistentVolumeClaim:
      claimName: my-pvc
