apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-app
  labels:
    app: secure-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-web-app
  template:
    metadata:
      labels:
        app: secure-web-app
    spec:
      containers:
      - name: app
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        # Environment variables from Secret
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: api-key
        volumeMounts:
        # Mount secret as volume
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
        # Mount TLS certificates
        - name: tls-volume
          mountPath: /etc/ssl/certs
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: app-secret
          defaultMode: 0400  # Read-only for owner
      - name: tls-volume
        secret:
          secretName: tls-secret
