apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: web-app
type: Opaque
data:
  # Base64 encoded values
  username: YWRtaW4=  # admin
  password: cGFzc3dvcmQxMjM=  # password123
  api-key: bXlfc3VwZXJfc2VjcmV0X2FwaV9rZXlfMTIzNDU=  # my_super_secret_api_key_12345
  database-password: ZGJwYXNzd29yZDQ1Ng==  # dbpassword456


