apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  labels:
    app: web-app
type: kubernetes.io/tls
data:
  # Note: In real usage, you'd put actual certificate data here
  # For demo purposes, these are placeholder values
  # Generate real certs with: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt
  tls.crt: LS0tLS1CRUdJTi... # Your certificate (base64 encoded)
  tls.key: LS0tLS1CRUdJTi... # Your private key (base64 encoded)

