apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  labels:
    app: hostpath-demo
spec:
  containers:
  - name: app
    image: nginx:1.21
    ports:
    - containerPort: 80
    volumeMounts:
    - name: host-data
      mountPath: /host-data
    - name: host-logs
      mountPath: /var/log/nginx
  volumes:
  - name: host-data
    hostPath:
      path: /tmp/k8s-host-data
      type: DirectoryOrCreate
  - name: host-logs
    hostPath:
      path: /tmp/k8s-nginx-logs
      type: DirectoryOrCreate
