apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    app: secret-volume-demo
spec:
  containers:
  - name: app
    image: nginx:1.21
    ports:
    - containerPort: 80
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
    - name: tls-certs
      mountPath: /etc/ssl/private
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: db-credentials
      defaultMode: 0400
  - name: tls-certs
    secret:
      secretName: tls-certificates
      items:
      - key: tls.crt
        path: server.crt
      - key: tls.key
        path: server.key
