apiVersion: v1
kind: Service
metadata:
  name: web-clusterip
  labels:
    app: web-app
    service-type: clusterip
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None
