apiVersion: v1
kind: Service
metadata:
  name: web-nodeport
  labels:
    app: web-app
    service-type: nodeport
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  externalTrafficPolicy: Cluster
